// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace backend.Models;

public partial class GradesClassesAppContext : DbContext
{
    public GradesClassesAppContext(DbContextOptions<GradesClassesAppContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Odeljenja> Odeljenja { get; set; }

    public virtual DbSet<Razredi> Razredi { get; set; }

    public virtual DbSet<Sifrarnici> Sifrarnici { get; set; }

    public virtual DbSet<StavkeSifrarnika> StavkeSifrarnika { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Odeljenja>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Odeljenj__3214EC07348B3A15");

            entity.ToTable(tb =>
                {
                    tb.HasTrigger("odeljenja_Insert_DatumUnosa");
                    tb.HasTrigger("odeljenja_Update_DatumIzmene");
                    tb.HasTrigger("updateRazrediUkupanBrojUcenikaIOdeljenjaOnOdeljenjeDelete");
                    tb.HasTrigger("update_BrojUcenika");
                    tb.HasTrigger("update_UkupanBrojOdeljenja_Razredi");
                    tb.HasTrigger("update_UkupanBrojUcenika_Razredi");
                });

            entity.Property(e => e.DatumIzmene).HasColumnType("datetime");
            entity.Property(e => e.DatumUnosa).HasColumnType("datetime");
            entity.Property(e => e.Naziv)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.NazivIzdvojeneSkole)
                .HasMaxLength(50)
                .HasDefaultValue("");
            entity.Property(e => e.OdeljenjskiStaresina).HasMaxLength(50);
            entity.Property(e => e.Smena).HasMaxLength(50);

            entity.HasOne(d => d.JezikNastave).WithMany(p => p.OdeljenjaJezikNastave)
                .HasForeignKey(d => d.JezikNastaveId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Odeljenja__Jezik__66603565");

            entity.HasOne(d => d.PrviStraniJezik).WithMany(p => p.OdeljenjaPrviStraniJezik)
                .HasForeignKey(d => d.PrviStraniJezikId)
                .HasConstraintName("FK__Odeljenja__PrviS__6754599E");

            entity.HasOne(d => d.Razred).WithMany(p => p.Odeljenja)
                .HasForeignKey(d => d.RazredId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Odeljenja__Razre__6477ECF3");

            entity.HasOne(d => d.VrstaOdeljenja).WithMany(p => p.OdeljenjaVrstaOdeljenja)
                .HasForeignKey(d => d.VrstaOdeljenjaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Odeljenja__Vrsta__656C112C");
        });

        modelBuilder.Entity<Razredi>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Razredi__3214EC07694A1B69");

            entity.ToTable(tb =>
                {
                    tb.HasTrigger("razredi_Insert_DatumUnosa");
                    tb.HasTrigger("razredi_Update_DatumIzmene");
                });

            entity.Property(e => e.DatumIzmene).HasColumnType("datetime");
            entity.Property(e => e.DatumUnosa).HasColumnType("datetime");

            entity.HasOne(d => d.Program).WithMany(p => p.RazrediProgram)
                .HasForeignKey(d => d.ProgramId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Razredi__Program__5BE2A6F2");

            entity.HasOne(d => d.Razred).WithMany(p => p.RazrediRazred)
                .HasForeignKey(d => d.RazredId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Razredi__RazredI__5AEE82B9");

            entity.HasOne(d => d.SkolskaGodina).WithMany(p => p.RazrediSkolskaGodina)
                .HasForeignKey(d => d.SkolskaGodinaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Razredi__Skolska__59FA5E80");
        });

        modelBuilder.Entity<Sifrarnici>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Sifrarni__3214EC076083BEDD");

            entity.ToTable(tb =>
                {
                    tb.HasTrigger("trg_Sifrarnici_Insert_DatumUnosa");
                    tb.HasTrigger("trg_Sifrarnici_Update_DatumIzmene");
                });

            entity.Property(e => e.DatumIzmene).HasColumnType("datetime");
            entity.Property(e => e.DatumUnosa).HasColumnType("datetime");
            entity.Property(e => e.Kategorija)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<StavkeSifrarnika>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__StavkeSi__3214EC0725A766BA");

            entity.ToTable(tb =>
                {
                    tb.HasTrigger("trg_StavkeSifrarnika_Insert_DatumUnosa");
                    tb.HasTrigger("trg_StavkeSifrarnika_Update_DatumIzmene");
                });

            entity.Property(e => e.DatumIzmene).HasColumnType("datetime");
            entity.Property(e => e.DatumUnosa).HasColumnType("datetime");
            entity.Property(e => e.Vrednost)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Sifrarnik).WithMany(p => p.StavkeSifrarnika)
                .HasForeignKey(d => d.SifrarnikId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__StavkeSif__Sifra__571DF1D5");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}