// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace backend.Models;

public partial class Odeljenja
{
    public int Id { get; set; }

    public int RazredId { get; set; }

    public string Naziv { get; set; }

    public int VrstaOdeljenjaId { get; set; }

    public bool Kombinovano { get; set; }

    public bool CelodnevnaNastava { get; set; }

    public bool IzdvojenoOdeljenje { get; set; }

    public string NazivIzdvojeneSkole { get; set; }

    public string OdeljenjskiStaresina { get; set; }

    public string Smena { get; set; }

    public int JezikNastaveId { get; set; }

    public bool Dvojezicno { get; set; }

    public int? PrviStraniJezikId { get; set; }

    public int BrojUcenika { get; set; }

    public int BrojDecaka { get; set; }

    public int BrojDevojcica { get; set; }

    public DateTime DatumUnosa { get; set; }

    public DateTime DatumIzmene { get; set; }

    public virtual StavkeSifrarnika JezikNastave { get; set; }

    public virtual StavkeSifrarnika PrviStraniJezik { get; set; }

    public virtual Razredi Razred { get; set; }

    public virtual StavkeSifrarnika VrstaOdeljenja { get; set; }
}