// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace backend.Models;

public partial class Razredi
{
    public int Id { get; set; }

    public int SkolskaGodinaId { get; set; }

    public int RazredId { get; set; }

    public int ProgramId { get; set; }

    public int UkupanBrojUcenika { get; set; }

    public int UkupanBrojOdeljenja { get; set; }

    public DateTime DatumUnosa { get; set; }

    public DateTime DatumIzmene { get; set; }

    public virtual ICollection<Odeljenja> Odeljenja { get; set; } = new List<Odeljenja>();

    public virtual StavkeSifrarnika Program { get; set; }

    public virtual StavkeSifrarnika Razred { get; set; }

    public virtual StavkeSifrarnika SkolskaGodina { get; set; }
}