// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace backend.Models;

public partial class Sifrarnici
{
    public int Id { get; set; }

    public string Kategorija { get; set; }

    public DateTime DatumUnosa { get; set; }

    public DateTime DatumIzmene { get; set; }

    public virtual ICollection<StavkeSifrarnika> StavkeSifrarnika { get; set; } = new List<StavkeSifrarnika>();
}