// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace backend.Models;

public partial class StavkeSifrarnika
{
    public int Id { get; set; }

    public int SifrarnikId { get; set; }

    public string Vrednost { get; set; }

    public DateTime DatumUnosa { get; set; }

    public DateTime DatumIzmene { get; set; }

    public virtual ICollection<Odeljenja> OdeljenjaJezikNastave { get; set; } = new List<Odeljenja>();

    public virtual ICollection<Odeljenja> OdeljenjaPrviStraniJezik { get; set; } = new List<Odeljenja>();

    public virtual ICollection<Odeljenja> OdeljenjaVrstaOdeljenja { get; set; } = new List<Odeljenja>();

    public virtual ICollection<Razredi> RazrediProgram { get; set; } = new List<Razredi>();

    public virtual ICollection<Razredi> RazrediRazred { get; set; } = new List<Razredi>();

    public virtual ICollection<Razredi> RazrediSkolskaGodina { get; set; } = new List<Razredi>();

    public virtual Sifrarnici Sifrarnik { get; set; }
}